# Generated by Django 2.2.5 on 2019-09-28 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects-images/')),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_num', models.IntegerField()),
                ('shot_num', models.IntegerField()),
                ('shot_desc', models.CharField(max_length=100)),
                ('shot_type', models.CharField(max_length=50)),
                ('shot_size', models.IntegerField(choices=[(1, 'Close Up Shot'), (2, 'Long Shot'), (3, 'Medium Shot')], default=1)),
                ('movement', models.IntegerField(choices=[(1, 'Static'), (2, 'Pan'), (3, 'Tilt'), (4, 'Tracking')], default=1)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviebinder.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_title', models.CharField(max_length=100)),
                ('script_content', models.TextField()),
                ('edited_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviebinder.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_no', models.IntegerField()),
                ('scene_type', models.IntegerField(choices=[(1, 'Interior'), (2, 'Exterior'), (3, 'Interior/Exterior')], default=1)),
                ('scene_desc', models.CharField(max_length=100)),
                ('mode', models.IntegerField(choices=[(1, 'Day'), (2, 'Night'), (3, 'Morning'), (4, 'Afternoon'), (5, 'Evening'), (6, 'Sunrise'), (7, 'Sunset')], default=1)),
                ('location', models.CharField(max_length=100)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviebinder.Project')),
            ],
        ),
    ]
